[package]
name = "cmakegen"
description = "Tool to generate cmake files"
authors = ["Will Lane <williamlane923@gmail.com>"]
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
toml = "0.5.8"
clap = "3.0.0-beta.2"
